version: 0.2

phases:
  install:
    commands:
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update
      - apt-get install -y openjdk-8-jdk python
      - java -version
      - echo $JAVA_HOME
  pre_build:
    commands:
      - docker run hello-world
      - mkdir ~/.gradle/
      - echo cacheUser = $CACHE_USER > ~/.gradle/gradle.properties
      - echo cachePassword = $CACHE_PASSWORD >> ~/.gradle/gradle.properties
      - echo systemProp.javax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts >> ~/.gradle/gradle.properties
      - echo systemProp.javax.net.ssl.trustStorePassword=changeit >> ~/.gradle/gradle.properties
      - docker-compose version
  build:
    commands:
      - echo Build started on `date`
      - chmod a+x gradlew
      - ls -la
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`
      - mv build/libs/zevrant-discovery-service-0.0.1-SNAPSHOT.jar build/libs/zevrant-discovery-service.jar
      - 
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
    
artifacts:
  files:
    - build/libs/zevrant-discovery-service.jar
