version: 0.2

phases:
  install:
    commands:
      - echo $JAVA_HOME
  pre_build:
    commands:
      - mkdir ~/.gradle/
      - echo cacheUser = $CACHE_USER > ~/.gradle/gradle.properties
      - echo cachePassword = $CACHE_PASSWORD >> ~/.gradle/gradle.properties
  build:
    commands:
      - echo Build started on `date`
      - chmod a+x gradlew
      - ls -la
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`
      - mv build/libs/zevrant-discovery-service-0.0.1-SNAPSHOT.jar:latest .
      - DOCKER_LOGIN=`aws ecr get-login --region us-east-1 --no-include-email`
      - eval $DOCKER_LOGIN
      - docker push 725235728275.dkr.ecr.us-east-1.amazonaws.com/zevrant-discovery-service:latest
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
    
